echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "I am working in REQ092348"
echo "I have learnt Github and Git"
echo "New Change for New Learnings"
echo "Github Actions"
echo "Github CHN0112 branch added"
echo "Github MAN555 branch added"
echo "New Merge Request on 06/05/2025"

